resources:
  - name:       Git
    type:       GitRepo
    configuration:
      gitProvider:  shahin_test
      path:         shahiinn/pipeline-successful-test     

pipelines:
  - name: pipe1
    steps:
    - name: try1
      type: Bash            
      configuration:
        affinityGroup: hello_docker
        inputResources:
            - name: Git       
      execution:
          onExecute:
            - echo "hey, I am running"
            - echo "FROM hello-world" > Dockerfile
            - source ${res_Git_resourcePath}/custom.sh
          onSuccess:
            - 'update_commit_status_custom Git --context "${step_name}" --message "test1 \n URL : test url" --url "https://google.com"'
            - 'update_commit_status_custom Git --context "${step_name}" --message "Image scan result: " --url "https://google.com"'
          onFailure:
            - echo "uh oh, something went wrong."
          onComplete: #always
            - echo "Cleaning up some stuff."
          onCancel:
            - echo "Someone cancelled the job......."


#    - name: build_image
#      type: DockerBuild
#      configuration:
#        affinityGroup: hello_docker
#        dockerFileLocation: .
#        dockerFileName: Dockerfile
#        dockerImageName: "10.70.30.71:8082/docker-local/pp-centos"
#        dockerImageTag: ${run_number}
#        inputSteps:
#          - name: try1
#        inputResources:
#          - name: Git
#        integrations:
#          - name: MyArtifactory

#    - name: push_image
#      type: DockerPush
#      configuration:
#        affinityGroup: hello_docker
#        targetRepository: "docker-local"
#        inputSteps:
#          - name: build_image
#        integrations:
#          - name: MyArtifactory
