resources: 

  - name:       Git
    type:       GitRepo
    configuration:
      gitProvider:  shahin_git
      path:         shahiinn/pipeline-successful-test  

pipelines:
  - name: pipe1
    configuration:
      environmentVariables:
        readOnly:
          SKIP_HELM: NO
    steps:
    - name: try1
      type: Bash            
      configuration:
        affinityGroup: hello_docker
        inputResources:
            - name: Git
      execution:
          onExecute:
            - echo "hey, I am running"
          onSuccess:
            - 'update_commit_status_custom Git --context "${step_name}" --message "test1 \n URL : test url" --url "https://google.com"'
            - 'update_commit_status_custom Git --context "${step_name} Image scan result:" --message "\t\t\t ===>> " --url "https://google.com/test"'
          onFailure:
            - echo "uh oh, something went wrong."
          onComplete: #always
            - echo "Cleaning up some stuff."
          onCancel:
            - echo "Someone cancelled the job."


    - name: try2
      type: Bash            
      configuration:
        affinityGroup: hello_docker
        inputSteps:
            - name: try1
        inputResources:
            - name: Git
      execution:
          onExecute:
            - |
              if [[ "${SKIP_HELM}" == "YES" || "${SKIP_HELM}" == "yes" ]]; then
                echo "Helm chart build is disabled. Skipping"
                exit 0
              fi
            - echo "hey, I am running new"



#    - name: build_image
#      type: DockerBuild
#      configuration:
#        affinityGroup: hello_docker
#        dockerFileLocation: .
#        dockerFileName: Dockerfile
#        dockerImageName: "10.70.30.71:8082/docker-local/pp-centos"
#        dockerImageTag: ${run_number}
#        inputSteps:
#          - name: try1
#        inputResources:
#          - name: Git
#        integrations:
#          - name: MyArtifactory

#    - name: push_image
#      type: DockerPush
#      configuration:
#        affinityGroup: hello_docker
#        targetRepository: "docker-local"
#        inputSteps:
#          - name: build_image
#        integrations:
#          - name: MyArtifactory
